version: '3.9'

services:
  web:
    build: database/.
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./database/src:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres




